# AUTOMATICALLY GENERATED by `shtab`



complete __main__.py \
        'c/--/(disable help keyring-backend keyring-path list-backends mode output print-completion)/' \
        'c/-/(- b h p)/' \
        'n/-p/d/' \
        'n/--keyring-path/d/' \
        'n/--mode/(password creds)/' \
        'n/--output/(plain json)/' \
        'n/--print-completion/(bash zsh tcsh)/' \
        'p/1/(get set del diagnose)/' \
        'p/*/()/'
